// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delivery.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delivery struct {
	DeliveryId           string   `protobuf:"bytes,1,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delivery) Reset()         { *m = Delivery{} }
func (m *Delivery) String() string { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()    {}
func (*Delivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf387bcb4e23d880, []int{0}
}

func (m *Delivery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delivery.Unmarshal(m, b)
}
func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delivery.Marshal(b, m, deterministic)
}
func (m *Delivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delivery.Merge(m, src)
}
func (m *Delivery) XXX_Size() int {
	return xxx_messageInfo_Delivery.Size(m)
}
func (m *Delivery) XXX_DiscardUnknown() {
	xxx_messageInfo_Delivery.DiscardUnknown(m)
}

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetDeliveryId() string {
	if m != nil {
		return m.DeliveryId
	}
	return ""
}

func (m *Delivery) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Delivery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Delivery) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*Delivery)(nil), "pb.Delivery")
}

func init() { proto.RegisterFile("delivery.proto", fileDescriptor_bf387bcb4e23d880) }

var fileDescriptor_bf387bcb4e23d880 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xd7, 0x39, 0x47, 0x77, 0x1c, 0x0e, 0x0e, 0x22, 0xa5, 0x82, 0x48, 0xaf, 0x76, 0x95,
	0x89, 0x7b, 0x84, 0xe9, 0x85, 0x57, 0x4a, 0x7d, 0x82, 0x65, 0x3d, 0xeb, 0x02, 0x4d, 0x4e, 0xc8,
	0xb2, 0x82, 0x4f, 0xec, 0x6b, 0x48, 0xd3, 0x65, 0xa8, 0x30, 0xef, 0xce, 0xff, 0xe5, 0xff, 0x4f,
	0xf8, 0x0f, 0x5c, 0x57, 0xd4, 0xa8, 0x96, 0xdc, 0xa7, 0xb0, 0x8e, 0x3d, 0xe3, 0xd0, 0xca, 0xfc,
	0xae, 0x66, 0xae, 0x1b, 0x5a, 0x04, 0x22, 0x0f, 0xdb, 0x05, 0x69, 0xeb, 0x8f, 0x86, 0xfc, 0x8a,
	0x5d, 0x45, 0xae, 0x17, 0x85, 0x85, 0xf4, 0xf9, 0x98, 0xc7, 0x7b, 0x80, 0xb8, 0xeb, 0xb5, 0xca,
	0x92, 0x87, 0x64, 0x3e, 0x29, 0x7f, 0x10, 0xcc, 0x21, 0x6d, 0x78, 0xb3, 0xf6, 0x8a, 0x4d, 0x36,
	0x0c, 0xaf, 0x27, 0x8d, 0x08, 0x23, 0xb3, 0xd6, 0x94, 0x5d, 0x04, 0x1e, 0x66, 0xbc, 0x81, 0x4b,
	0xbb, 0x63, 0x43, 0xd9, 0x28, 0xc0, 0x5e, 0x3c, 0x7d, 0x25, 0x30, 0x8b, 0x5f, 0x7e, 0x90, 0x6b,
	0xd5, 0x86, 0x70, 0x0e, 0x69, 0x49, 0xb5, 0xda, 0x7b, 0x72, 0x38, 0x15, 0x56, 0x8a, 0x68, 0xc8,
	0x7f, 0xa9, 0x62, 0x80, 0x8f, 0x30, 0x2e, 0x49, 0x73, 0x4b, 0x7f, 0x7c, 0xb7, 0xa2, 0xaf, 0x2c,
	0x62, 0x65, 0xf1, 0xd2, 0x55, 0x2e, 0x06, 0xb8, 0x84, 0xe9, 0xfb, 0x41, 0x36, 0x6a, 0xbf, 0x7b,
	0xeb, 0x7a, 0xe3, 0xa4, 0xcb, 0x85, 0xf1, 0x9f, 0xd0, 0x0a, 0x66, 0x2b, 0x36, 0x5b, 0xe5, 0xf4,
	0xe9, 0x3a, 0x67, 0xcc, 0xe7, 0x97, 0xc8, 0x71, 0x20, 0xcb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xac, 0x61, 0x11, 0x42, 0xa2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	Register(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error)
	Remove(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*empty.Empty, error)
	PublishOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*empty.Empty, error)
	ConfirmDelivery(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type deliveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeliveryServiceClient(cc *grpc.ClientConn) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) Register(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error) {
	out := new(Delivery)
	err := c.cc.Invoke(ctx, "/pb.DeliveryService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) Remove(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.DeliveryService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) PublishOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.DeliveryService/PublishOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ConfirmDelivery(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.DeliveryService/ConfirmDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
type DeliveryServiceServer interface {
	Register(context.Context, *Delivery) (*Delivery, error)
	Remove(context.Context, *Delivery) (*empty.Empty, error)
	PublishOrder(context.Context, *Order) (*empty.Empty, error)
	ConfirmDelivery(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedDeliveryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeliveryServiceServer struct {
}

func (*UnimplementedDeliveryServiceServer) Register(ctx context.Context, req *Delivery) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedDeliveryServiceServer) Remove(ctx context.Context, req *Delivery) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedDeliveryServiceServer) PublishOrder(ctx context.Context, req *Order) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishOrder not implemented")
}
func (*UnimplementedDeliveryServiceServer) ConfirmDelivery(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmDelivery not implemented")
}

func RegisterDeliveryServiceServer(s *grpc.Server, srv DeliveryServiceServer) {
	s.RegisterService(&_DeliveryService_serviceDesc, srv)
}

func _DeliveryService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DeliveryService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).Register(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DeliveryService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).Remove(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_PublishOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).PublishOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DeliveryService/PublishOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).PublishOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ConfirmDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ConfirmDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DeliveryService/ConfirmDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ConfirmDelivery(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeliveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DeliveryService_Register_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DeliveryService_Remove_Handler,
		},
		{
			MethodName: "PublishOrder",
			Handler:    _DeliveryService_PublishOrder_Handler,
		},
		{
			MethodName: "ConfirmDelivery",
			Handler:    _DeliveryService_ConfirmDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery.proto",
}
