// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order_Status int32

const (
	Order_NONE       Order_Status = 0
	Order_PLACED     Order_Status = 1
	Order_IN_TRANSIT Order_Status = 2
	Order_DELIVERED  Order_Status = 3
)

var Order_Status_name = map[int32]string{
	0: "NONE",
	1: "PLACED",
	2: "IN_TRANSIT",
	3: "DELIVERED",
}

var Order_Status_value = map[string]int32{
	"NONE":       0,
	"PLACED":     1,
	"IN_TRANSIT": 2,
	"DELIVERED":  3,
}

func (x Order_Status) String() string {
	return proto.EnumName(Order_Status_name, int32(x))
}

func (Order_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1, 0}
}

type CustomerInfo struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeliveryLocation     string   `protobuf:"bytes,3,opt,name=deliveryLocation,proto3" json:"deliveryLocation,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerInfo) Reset()         { *m = CustomerInfo{} }
func (m *CustomerInfo) String() string { return proto.CompactTextString(m) }
func (*CustomerInfo) ProtoMessage()    {}
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *CustomerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerInfo.Unmarshal(m, b)
}
func (m *CustomerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerInfo.Marshal(b, m, deterministic)
}
func (m *CustomerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerInfo.Merge(m, src)
}
func (m *CustomerInfo) XXX_Size() int {
	return xxx_messageInfo_CustomerInfo.Size(m)
}
func (m *CustomerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerInfo proto.InternalMessageInfo

func (m *CustomerInfo) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *CustomerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerInfo) GetDeliveryLocation() string {
	if m != nil {
		return m.DeliveryLocation
	}
	return ""
}

func (m *CustomerInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Order struct {
	OrderId              string        `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	StoreLocation        string        `protobuf:"bytes,2,opt,name=storeLocation,proto3" json:"storeLocation,omitempty"`
	Customer             *CustomerInfo `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Status               Order_Status  `protobuf:"varint,4,opt,name=status,proto3,enum=pb.Order_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetStoreLocation() string {
	if m != nil {
		return m.StoreLocation
	}
	return ""
}

func (m *Order) GetCustomer() *CustomerInfo {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Order) GetStatus() Order_Status {
	if m != nil {
		return m.Status
	}
	return Order_NONE
}

type OrderId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderId) Reset()         { *m = OrderId{} }
func (m *OrderId) String() string { return proto.CompactTextString(m) }
func (*OrderId) ProtoMessage()    {}
func (*OrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *OrderId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderId.Unmarshal(m, b)
}
func (m *OrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderId.Marshal(b, m, deterministic)
}
func (m *OrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderId.Merge(m, src)
}
func (m *OrderId) XXX_Size() int {
	return xxx_messageInfo_OrderId.Size(m)
}
func (m *OrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderId.DiscardUnknown(m)
}

var xxx_messageInfo_OrderId proto.InternalMessageInfo

func (m *OrderId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Order_Status", Order_Status_name, Order_Status_value)
	proto.RegisterType((*CustomerInfo)(nil), "pb.CustomerInfo")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*OrderId)(nil), "pb.OrderId")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x6b, 0xe2, 0x50,
	0x14, 0x35, 0x51, 0xa3, 0x5e, 0x35, 0x13, 0x2e, 0xc3, 0x90, 0x71, 0x60, 0x66, 0x08, 0x5d, 0x48,
	0x29, 0x91, 0xda, 0x45, 0xbb, 0xe9, 0x42, 0x4c, 0x28, 0x01, 0x89, 0x12, 0xa5, 0xdb, 0x92, 0x8f,
	0xa7, 0x0d, 0x68, 0x5e, 0x48, 0x9e, 0x82, 0xfb, 0xfe, 0xc5, 0x6e, 0xfb, 0x5b, 0x8a, 0xef, 0x99,
	0x54, 0x29, 0x5d, 0x74, 0x97, 0x7b, 0xce, 0x3d, 0xb9, 0xe7, 0xbc, 0x03, 0x6d, 0x9a, 0x45, 0x24,
	0x33, 0xd3, 0x8c, 0x32, 0x8a, 0x72, 0x1a, 0xf4, 0xfe, 0xac, 0x28, 0x5d, 0xad, 0xc9, 0x80, 0x23,
	0xc1, 0x76, 0x39, 0x20, 0x9b, 0x94, 0xed, 0xc5, 0x82, 0xf1, 0x22, 0x41, 0x67, 0xbc, 0xcd, 0x19,
	0xdd, 0x90, 0xcc, 0x49, 0x96, 0x14, 0xff, 0x02, 0x84, 0xc5, 0x1c, 0xe9, 0xd2, 0x7f, 0xa9, 0xdf,
	0xf2, 0x4e, 0x10, 0x44, 0xa8, 0x25, 0xfe, 0x86, 0xe8, 0x32, 0x67, 0xf8, 0x37, 0x5e, 0x82, 0x16,
	0x91, 0x75, 0xbc, 0x23, 0xd9, 0x7e, 0x42, 0x43, 0x9f, 0xc5, 0x34, 0xd1, 0xab, 0x9c, 0xff, 0x84,
	0xe3, 0x4f, 0xa8, 0xa7, 0xcf, 0x34, 0x21, 0x7a, 0x8d, 0x2f, 0x88, 0xc1, 0x78, 0x93, 0xa0, 0x3e,
	0x3d, 0xf8, 0x46, 0x1d, 0x1a, 0x3c, 0x40, 0x79, 0xbc, 0x18, 0xf1, 0x02, 0xba, 0x39, 0xa3, 0x19,
	0x29, 0x4f, 0x08, 0x0b, 0xe7, 0x20, 0x5e, 0x41, 0xb3, 0x70, 0xcb, 0x3d, 0xb4, 0x87, 0x9a, 0x99,
	0x06, 0xe6, 0x69, 0x46, 0xaf, 0xdc, 0xc0, 0x3e, 0x28, 0x39, 0xf3, 0xd9, 0x36, 0xe7, 0x76, 0x54,
	0xb1, 0xcb, 0x8d, 0x98, 0x73, 0x8e, 0x7b, 0x47, 0xde, 0xb8, 0x07, 0x45, 0x20, 0xd8, 0x84, 0x9a,
	0x3b, 0x75, 0x6d, 0xad, 0x82, 0x00, 0xca, 0x6c, 0x32, 0x1a, 0xdb, 0x96, 0x26, 0xa1, 0x0a, 0xe0,
	0xb8, 0x4f, 0x0b, 0x6f, 0xe4, 0xce, 0x9d, 0x85, 0x26, 0x63, 0x17, 0x5a, 0x96, 0x3d, 0x71, 0x1e,
	0x6d, 0xcf, 0xb6, 0xb4, 0xaa, 0xf1, 0x1b, 0x1a, 0xd3, 0x63, 0x0e, 0x15, 0xe4, 0xb8, 0x08, 0x27,
	0xc7, 0xd1, 0xf0, 0x55, 0x82, 0x0e, 0xe7, 0xe6, 0x24, 0xdb, 0xc5, 0x21, 0xc1, 0x7f, 0x50, 0x7d,
	0x20, 0x0c, 0xdb, 0xa5, 0x17, 0x27, 0xea, 0xb5, 0xca, 0xc1, 0xa8, 0xe0, 0x35, 0xc0, 0x6c, 0xed,
	0x87, 0x44, 0xbc, 0xd8, 0x07, 0xd5, 0xfb, 0x65, 0x8a, 0xae, 0xcd, 0xa2, 0x6b, 0xd3, 0x3e, 0x74,
	0x6d, 0x54, 0xf0, 0x0e, 0x7e, 0x58, 0xa2, 0x8a, 0x38, 0x59, 0x09, 0xdd, 0xd9, 0xff, 0xbf, 0x56,
	0xde, 0x82, 0x7a, 0x54, 0x92, 0xe8, 0x3b, 0xc2, 0x40, 0xe1, 0xc8, 0xcd, 0x7b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x39, 0xe5, 0x90, 0x5a, 0x91, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	//4. delivery guys click link, sees orders on webpage
	Get(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*Order, error)
	//1. calls delivery/PublishOrder
	PlaceOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*empty.Empty, error)
	//6. changes status of Order to IN_TRANSIT
	DeliveringOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*empty.Empty, error)
	//9. changes status of Order to DELIVERED
	DeliveredOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*empty.Empty, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) Get(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/pb.OrderService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) PlaceOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.OrderService/PlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeliveringOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.OrderService/DeliveringOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeliveredOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.OrderService/DeliveredOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	//4. delivery guys click link, sees orders on webpage
	Get(context.Context, *OrderId) (*Order, error)
	//1. calls delivery/PublishOrder
	PlaceOrder(context.Context, *Order) (*empty.Empty, error)
	//6. changes status of Order to IN_TRANSIT
	DeliveringOrder(context.Context, *OrderId) (*empty.Empty, error)
	//9. changes status of Order to DELIVERED
	DeliveredOrder(context.Context, *OrderId) (*empty.Empty, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) Get(ctx context.Context, req *OrderId) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedOrderServiceServer) PlaceOrder(ctx context.Context, req *Order) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (*UnimplementedOrderServiceServer) DeliveringOrder(ctx context.Context, req *OrderId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliveringOrder not implemented")
}
func (*UnimplementedOrderServiceServer) DeliveredOrder(ctx context.Context, req *OrderId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliveredOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Get(ctx, req.(*OrderId))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PlaceOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeliveringOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeliveringOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/DeliveringOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeliveringOrder(ctx, req.(*OrderId))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeliveredOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeliveredOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/DeliveredOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeliveredOrder(ctx, req.(*OrderId))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _OrderService_Get_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _OrderService_PlaceOrder_Handler,
		},
		{
			MethodName: "DeliveringOrder",
			Handler:    _OrderService_DeliveringOrder_Handler,
		},
		{
			MethodName: "DeliveredOrder",
			Handler:    _OrderService_DeliveredOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
