// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cart.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cart_Status int32

const (
	Cart_CREATED Cart_Status = 0
	Cart_PLACED  Cart_Status = 1
	Cart_SHIPPED Cart_Status = 2
)

var Cart_Status_name = map[int32]string{
	0: "CREATED",
	1: "PLACED",
	2: "SHIPPED",
}

var Cart_Status_value = map[string]int32{
	"CREATED": 0,
	"PLACED":  1,
	"SHIPPED": 2,
}

func (x Cart_Status) String() string {
	return proto.EnumName(Cart_Status_name, int32(x))
}

func (Cart_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{0, 0}
}

type Cart struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Products             map[string]int32 `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	TotalItems           int32            `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	TotalCost            float64          `protobuf:"fixed64,5,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	Status               Cart_Status      `protobuf:"varint,6,opt,name=status,proto3,enum=pb.Cart_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{0}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cart) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Cart) GetProducts() map[string]int32 {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Cart) GetTotalItems() int32 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *Cart) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *Cart) GetStatus() Cart_Status {
	if m != nil {
		return m.Status
	}
	return Cart_CREATED
}

type CartId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartId) Reset()         { *m = CartId{} }
func (m *CartId) String() string { return proto.CompactTextString(m) }
func (*CartId) ProtoMessage()    {}
func (*CartId) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{1}
}

func (m *CartId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartId.Unmarshal(m, b)
}
func (m *CartId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartId.Marshal(b, m, deterministic)
}
func (m *CartId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartId.Merge(m, src)
}
func (m *CartId) XXX_Size() int {
	return xxx_messageInfo_CartId.Size(m)
}
func (m *CartId) XXX_DiscardUnknown() {
	xxx_messageInfo_CartId.DiscardUnknown(m)
}

var xxx_messageInfo_CartId proto.InternalMessageInfo

func (m *CartId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Cart_Status", Cart_Status_name, Cart_Status_value)
	proto.RegisterType((*Cart)(nil), "pb.Cart")
	proto.RegisterMapType((map[string]int32)(nil), "pb.Cart.ProductsEntry")
	proto.RegisterType((*CartId)(nil), "pb.CartId")
}

func init() { proto.RegisterFile("cart.proto", fileDescriptor_bf731a5c8f9a516f) }

var fileDescriptor_bf731a5c8f9a516f = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0x8d, 0x9c, 0xc6, 0x6d, 0x6e, 0x68, 0x16, 0x2e, 0xa5, 0x98, 0x6c, 0x14, 0xcf, 0x2f, 0xf3,
	0xcb, 0x94, 0xe1, 0xbd, 0x8c, 0xed, 0x29, 0x38, 0x2e, 0x0b, 0x0c, 0x96, 0x39, 0xdd, 0xde, 0x95,
	0x48, 0x2b, 0x62, 0x8e, 0x65, 0x64, 0x39, 0x90, 0xff, 0xda, 0x07, 0xec, 0xd3, 0x86, 0x6c, 0x27,
	0x8b, 0x07, 0x85, 0xbe, 0x49, 0xe7, 0x1c, 0x9d, 0x73, 0xae, 0xaf, 0x01, 0xb6, 0x4c, 0x1b, 0x5a,
	0x68, 0x65, 0x14, 0x3a, 0xc5, 0x66, 0xfa, 0xf2, 0x51, 0xa9, 0xc7, 0x4c, 0xcc, 0x6a, 0x64, 0x53,
	0xfd, 0x9c, 0x89, 0x5d, 0x61, 0x0e, 0x8d, 0x60, 0x7a, 0x5d, 0x68, 0xc5, 0xab, 0x6d, 0xab, 0x0f,
	0xfe, 0x38, 0x70, 0x11, 0x33, 0x6d, 0x70, 0x0c, 0x8e, 0xe4, 0x1e, 0xf1, 0x49, 0x38, 0x4c, 0x1d,
	0xc9, 0xd1, 0x87, 0x11, 0x17, 0xe5, 0x56, 0xcb, 0xc2, 0x48, 0x95, 0x7b, 0x4e, 0x4d, 0x9c, 0x43,
	0x18, 0xc1, 0x55, 0xeb, 0x55, 0x7a, 0x7d, 0xbf, 0x1f, 0x8e, 0xa2, 0x5b, 0x5a, 0x6c, 0xa8, 0x75,
	0xa3, 0xab, 0x96, 0x48, 0x72, 0xa3, 0x0f, 0xe9, 0x49, 0x87, 0x77, 0x00, 0x46, 0x19, 0x96, 0x2d,
	0x8d, 0xd8, 0x95, 0xde, 0x85, 0x4f, 0xc2, 0x41, 0x7a, 0x86, 0xe0, 0x2b, 0x18, 0xd6, 0xb7, 0x58,
	0x95, 0xc6, 0x1b, 0xf8, 0x24, 0x24, 0xe9, 0x3f, 0x00, 0xdf, 0x80, 0x5b, 0x1a, 0x66, 0xaa, 0xd2,
	0x73, 0x7d, 0x12, 0x8e, 0xa3, 0x17, 0xa7, 0xbc, 0x75, 0x0d, 0xa7, 0x2d, 0x3d, 0xfd, 0x04, 0xd7,
	0x9d, 0x06, 0x38, 0x81, 0xfe, 0x2f, 0x71, 0x68, 0xc7, 0xb3, 0x47, 0xbc, 0x81, 0xc1, 0x9e, 0x65,
	0x95, 0xa8, 0x27, 0x1b, 0xa4, 0xcd, 0xe5, 0xa3, 0xf3, 0x81, 0x04, 0x14, 0xdc, 0xc6, 0x0e, 0x47,
	0x70, 0x19, 0xa7, 0xc9, 0xfc, 0x21, 0x59, 0x4c, 0x7a, 0x08, 0xe0, 0xae, 0xbe, 0xcc, 0xe3, 0x64,
	0x31, 0x21, 0x96, 0x58, 0x7f, 0x5e, 0xae, 0x56, 0xc9, 0x62, 0xe2, 0x04, 0x1e, 0xb8, 0xb6, 0xc3,
	0x92, 0xff, 0xff, 0x0d, 0xa3, 0xdf, 0x0e, 0x8c, 0x2c, 0xb5, 0x16, 0x7a, 0x2f, 0xb7, 0x02, 0xef,
	0xc0, 0x8d, 0xb5, 0x60, 0x46, 0xe0, 0xd5, 0xb1, 0xf9, 0xf4, 0x74, 0x0a, 0x7a, 0xf8, 0x1a, 0x2e,
	0xef, 0x65, 0xce, 0xbf, 0xe6, 0x02, 0xe1, 0x08, 0x2f, 0x79, 0x47, 0x32, 0x6b, 0x24, 0xf3, 0x2c,
	0xc3, 0x5b, 0xda, 0xec, 0x99, 0x1e, 0xf7, 0x4c, 0x13, 0xbb, 0xe7, 0x73, 0xf9, 0x3b, 0x62, 0x33,
	0xbf, 0x17, 0xfc, 0xe9, 0x4c, 0x0a, 0xee, 0x42, 0x64, 0xc2, 0x74, 0x23, 0x9f, 0xf0, 0x0e, 0x7a,
	0xf8, 0x16, 0x86, 0x73, 0xce, 0x1f, 0x54, 0xfd, 0xd3, 0xdc, 0xd8, 0x27, 0x3f, 0x58, 0x26, 0x6d,
	0xc0, 0xb7, 0x8a, 0xe5, 0x46, 0x76, 0x0b, 0x60, 0x04, 0xe3, 0x54, 0xec, 0xd4, 0x5e, 0xdc, 0x6b,
	0xb5, 0x7b, 0xde, 0x9b, 0x8d, 0x5b, 0x87, 0xbe, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x8d,
	0xe7, 0xb0, 0xd8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CartServiceClient interface {
	Create(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error)
	FindOne(ctx context.Context, in *CartId, opts ...grpc.CallOption) (*Cart, error)
	FindAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (CartService_FindAllClient, error)
	Update(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error)
	Delete(ctx context.Context, in *CartId, opts ...grpc.CallOption) (*empty.Empty, error)
	AddToCart(ctx context.Context, in *ValidateQuantity, opts ...grpc.CallOption) (*Cart, error)
	RemoveFromCart(ctx context.Context, in *ValidateQuantity, opts ...grpc.CallOption) (*Cart, error)
}

type cartServiceClient struct {
	cc *grpc.ClientConn
}

func NewCartServiceClient(cc *grpc.ClientConn) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) Create(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/pb.CartService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) FindOne(ctx context.Context, in *CartId, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/pb.CartService/FindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) FindAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (CartService_FindAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CartService_serviceDesc.Streams[0], "/pb.CartService/FindAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &cartServiceFindAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CartService_FindAllClient interface {
	Recv() (*Cart, error)
	grpc.ClientStream
}

type cartServiceFindAllClient struct {
	grpc.ClientStream
}

func (x *cartServiceFindAllClient) Recv() (*Cart, error) {
	m := new(Cart)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cartServiceClient) Update(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/pb.CartService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) Delete(ctx context.Context, in *CartId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.CartService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) AddToCart(ctx context.Context, in *ValidateQuantity, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/pb.CartService/AddToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) RemoveFromCart(ctx context.Context, in *ValidateQuantity, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/pb.CartService/RemoveFromCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
type CartServiceServer interface {
	Create(context.Context, *Cart) (*Cart, error)
	FindOne(context.Context, *CartId) (*Cart, error)
	FindAll(*empty.Empty, CartService_FindAllServer) error
	Update(context.Context, *Cart) (*Cart, error)
	Delete(context.Context, *CartId) (*empty.Empty, error)
	AddToCart(context.Context, *ValidateQuantity) (*Cart, error)
	RemoveFromCart(context.Context, *ValidateQuantity) (*Cart, error)
}

// UnimplementedCartServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCartServiceServer struct {
}

func (*UnimplementedCartServiceServer) Create(ctx context.Context, req *Cart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCartServiceServer) FindOne(ctx context.Context, req *CartId) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedCartServiceServer) FindAll(req *empty.Empty, srv CartService_FindAllServer) error {
	return status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (*UnimplementedCartServiceServer) Update(ctx context.Context, req *Cart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCartServiceServer) Delete(ctx context.Context, req *CartId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedCartServiceServer) AddToCart(ctx context.Context, req *ValidateQuantity) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (*UnimplementedCartServiceServer) RemoveFromCart(ctx context.Context, req *ValidateQuantity) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromCart not implemented")
}

func RegisterCartServiceServer(s *grpc.Server, srv CartServiceServer) {
	s.RegisterService(&_CartService_serviceDesc, srv)
}

func _CartService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CartService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Create(ctx, req.(*Cart))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CartService/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).FindOne(ctx, req.(*CartId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_FindAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CartServiceServer).FindAll(m, &cartServiceFindAllServer{stream})
}

type CartService_FindAllServer interface {
	Send(*Cart) error
	grpc.ServerStream
}

type cartServiceFindAllServer struct {
	grpc.ServerStream
}

func (x *cartServiceFindAllServer) Send(m *Cart) error {
	return x.ServerStream.SendMsg(m)
}

func _CartService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CartService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Update(ctx, req.(*Cart))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CartService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Delete(ctx, req.(*CartId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQuantity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CartService/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).AddToCart(ctx, req.(*ValidateQuantity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_RemoveFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQuantity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).RemoveFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CartService/RemoveFromCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).RemoveFromCart(ctx, req.(*ValidateQuantity))
	}
	return interceptor(ctx, in, info, handler)
}

var _CartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CartService_Create_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _CartService_FindOne_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CartService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CartService_Delete_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _CartService_AddToCart_Handler,
		},
		{
			MethodName: "RemoveFromCart",
			Handler:    _CartService_RemoveFromCart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindAll",
			Handler:       _CartService_FindAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cart.proto",
}
